Repository Dcbaas/Monopoly-Project-CIS350-G3, pull requests merged in 2018-03, with the labels that each got.

#89 Created tests for the Deck class
  Tests/Model/CardPackage/DeckTest.java
  src/Model/CardPackage/Deck.java
Labels: test

#90 Game Class
  src/Model/BoardPackage/GoSquare.java
  src/Model/BoardPackage/OwnableSquare.java
  src/Model/BoardPackage/PropertySquare.java
  src/Model/GamePackage/Game.java
  src/Model/GamePackage/Player.java
Labels: feature

#93 Feature/92/create text interface
  Tests/Model/BoardPackage/BoardSquareTest.java
  Tests/Model/BoardPackage/OwnableSquareTest.java
  Tests/Model/GamePackage/BankTest.java
  Tests/Model/GamePackage/PlayerTest.java
  src/Controller/GameTextController.java
  src/Model/GamePackage/Game.java
  src/MonopolyGame.java
  src/View/GameTextView.java
Labels: feature

#105 Feature/95 implement next player
  Tests/Model/BoardPackage/BoardTest.java
  src/Controller/GameTextController.java
  src/Model/BoardPackage/Board.java
  src/Model/GamePackage/Game.java
  src/MonopolyGame.java
  src/View/GameTextView.java
Labels: feature

#106 Feature/104 implement next turn
  src/Controller/GameTextController.java
Labels: feature

#107 Cleaned up prints, added possibleActions method and print
  src/Controller/GameTextController.java
  src/MonopolyGame.java
  src/View/GameTextView.java
Labels: feature

#108 Added feature to print wallet amount when list command is entered
  src/Controller/GameTextController.java
  src/View/GameTextView.java
Labels: feature

#111 Feature/98 implement tax
  src/Controller/GameTextController.java
  src/Model/GamePackage/Game.java
  src/Model/GamePackage/Player.java
  src/View/GameTextView.java
Labels: feature

#112 Feature/110/build house and hotel
  src/Controller/GameTextController.java
  src/Model/GamePackage/Game.java
  src/Model/GamePackage/Player.java
  src/MonopolyGame.java
  src/View/GameTextView.java
Labels: feature

#114 Bug/113 fix tax implementation
  src/Controller/GameTextController.java
  src/Model/BoardPackage/Board.java
  src/Model/GamePackage/Game.java
Labels: bug

#122 Feature/96 implement mortgage
  src/Controller/GameTextController.java
  src/MonopolyGame.java
  src/View/GameTextView.java
Labels: feature

#128 Changed all string formats to use %n not \n
  src/View/GameTextView.java
Labels: bug

#126 Feature/123 create a demo board space
  Tests/Veiw/PropertySpaceTest.java
  res/MonopolyHotel.png
  res/MonopolyHouse.png
  src/View/HousingPanel.java
  src/View/PropertySpace.java
Labels: feature

#143 Feature/141 flush out property board space
  Tests/Veiw/PropertySpaceDemo.java
  src/View/HousingPanel.java
  src/View/PropertySpace.java
Labels: feature

#145 Feature/129&130 Create CardSpace
  res/chance.png
  res/community-chest.png
  src/View/CardSpace.java
Labels: feature

#144 Feature/131 create rr board space
  res/Monopoly RR.jpg
  src/View/RailRoadSpace.java
Labels: feature

#148 Created Free Parking Square panel
  res/freeParkingImg.png
  src/View/FreeParkingSpace.java
Labels: feature

#150 Feature/133 create utilities board space
  res/electricCompany.jpg
  res/waterWorks.png
  src/View/UtilitiesSpace.java
Labels: feature

#154 Wrote Game class tests. Miner fix to game class
  Tests/Model/GamePackage/GameTest.java
  src/Model/GamePackage/Game.java
Labels: test

#156 Feature/153 create game panel
  res/MonopolyLogo.jpg
  src/View/CardSpace.java
  src/View/CenterImage.java
  src/View/FreeParkingSpace.java
  src/View/GamePanel.java
  src/View/GoSpace.java
  src/View/GoToJailSpace.java
  src/View/HousingPanel.java
  src/View/JailSpace.java
  src/View/PropertySpace.java
  src/View/RailRoadSpace.java
  src/View/TaxSpace.java
  src/View/UtilitiesSpace.java
Labels: feature

#158 Feature/157/finish card functionality
  res/board.txt
  src/Controller/GameTextController.java
  src/Model/GamePackage/Game.java
  src/MonopolyGame.java
  src/View/GameTextView.java
Labels: feature

#160 Fixed Bug
  src/View/CenterImage.java
  src/View/FreeParkingSpace.java
  src/View/GamePanel.java
  src/View/GoSpace.java
  src/View/GoToJailSpace.java
  src/View/JailSpace.java
  src/View/TaxSpace.java
Labels: bug
