Repository Dcbaas/Monopoly-Project-CIS350-G3, pull requests merged in 2018-02, with the labels that each got.

#36 Feature/12 Wrote BoardSquare Interface
  Model/src/BoardPackage/BoardSquare.java
Labels: feature

#41 Feature/13 Wrote PropertySquare Class
  Model/src/BoardPackage/PropertySquare.java
Labels: feature

#43 Wrote RailRoadSquare Class
  Model/src/BoardPackage/RailRoadSquare.java
Labels: feature

#52 Wrote GoToJailSquare Class
  Model/src/BoardPackage/GoToJailSquare.java
Labels: feature

#50 Wrote GoSquare Class.
  Model/src/BoardPackage/GoSquare.java
Labels: feature

#48 Feature/48 Wrote FreeParkingSquare Class
  Model/src/BoardPackage/FreeParkingSquare.java
Labels: feature

#45 Wrote basic bank class
  Model/src/GamePackage/Bank.java
Labels: feature

#42 Feature/15 write player class
  Model/src/GamePackage/Player.java
Labels: feature

#47 Feature/44 Wrote JailSquare Class.
  Model/src/BoardPackage/JailSquare.java
Labels: feature

#56 Wrote UtilitiesSquare class
  src/Model/BoardPackage/UtilitiesSquare.java
Labels: feature

#58 Feature/19 write card class
  src/Model/CardPackage/Card.java
Labels: feature

#57 Feature/55 create ownable square class
  src/Model/BoardPackage/BoardSquare.java
  src/Model/BoardPackage/FreeParkingSquare.java
  src/Model/BoardPackage/GoSquare.java
  src/Model/BoardPackage/GoToJailSquare.java
  src/Model/BoardPackage/JailSquare.java
  src/Model/BoardPackage/OwnableSquare.java
  src/Model/BoardPackage/PropertySquare.java
  src/Model/BoardPackage/RailRoadSquare.java
  src/Model/BoardPackage/UtilitiesSquare.java
  src/Model/GamePackage/Bank.java
  src/Model/GamePackage/Player.java
Labels: enhancement, feature

#62 Added GROUP_NUMBER, added it as a param for construcotr, and made getter
  src/Model/BoardPackage/OwnableSquare.java
Labels: feature

#63 Added inJail, and groupsOwned
  src/Model/GamePackage/Player.java
Labels: feature

#61 Feature/46 write board class
  Model/src/GamePackage/Player.java
  res/board.txt
  res/chance.txt
  res/community.txt
  res/properties.txt
  res/railroads.txt
  res/utillities.txt
  src/Model/BoardPackage/Board.java
  src/Model/GamePackage/Bank.java
  src/mainTest.java
Labels: feature

#65 Added groupNumber to individual square classes
  src/Model/BoardPackage/PropertySquare.java
  src/Model/BoardPackage/RailRoadSquare.java
  src/Model/BoardPackage/UtilitiesSquare.java
Labels: bug, feature

#67 Fixed return value of giveProperty. Also fixed same issue in Bank
  src/Model/GamePackage/Bank.java
  src/Model/GamePackage/Player.java
Labels: bug

#69 Feature/21 write deck class
  Tests/Model/GamePackage/DieTest.java
  lib/hamcrest-core-1.3.jar
  lib/junit-4.12.jar
  src/Model/BoardPackage/Board.java
  src/Model/CardPackage/Deck.java
  src/mainTest.java
Labels: feature

#81 Revised comments for Bank, Die, and Player Classes.
  src/Model/BoardPackage/Board.java
  src/Model/GamePackage/Bank.java
  src/Model/GamePackage/Die.java
Labels: enhancement

#80 Test/16/write unit test for player class
  Tests/Model/GamePackage/DieTest.java
  Tests/Model/GamePackage/PlayerTest.java
  src/Model/BoardPackage/Board.java
  src/Model/CardPackage/Deck.java
  src/Model/GamePackage/Game.java
  src/Model/GamePackage/Player.java
  src/mainTest.java
Labels: test

#85 Test/73/writ unit test for board square class
  Tests/Model/BoardPackage/BoardSquareTest.java
Labels: test

#86 Wrote unit tests for Bank class
  Tests/Model/GamePackage/BankTest.java
Labels: test

#87 Wrote unit tests for Board Class. Also created a txt file used in tests
  Tests/Model/BoardPackage/BoardTest.java
  res/testBoard.txt
Labels: test
