Repository Dcbaas/Monopoly-Project-CIS350-G3, pull requests merged in 2018-04, with the labels that each got.

#166 Feature/162 implement player movement
  src/TestView.java
  src/View/BoardSpaces/CardSpace.java
  src/View/BoardSpaces/FreeParkingSpace.java
  src/View/BoardSpaces/GoSpace.java
  src/View/BoardSpaces/GoToJailSpace.java
  src/View/BoardSpaces/JailSpace.java
  src/View/BoardSpaces/PropertySpace.java
  src/View/BoardSpaces/RailRoadSpace.java
  src/View/BoardSpaces/Spaces.java
  src/View/BoardSpaces/TaxSpace.java
  src/View/BoardSpaces/UtilitiesSpace.java
  src/View/GamePanel.java
  src/View/GameView.java
  src/View/PlayerToken.java
Labels: feature

#169 Feature/syntax
  src/Model/CardPackage/Card.java
  src/Model/GamePackage/Game.java
  src/Model/GamePackage/Player.java
Labels: feature

#173 Feature/167 reorganize game view
  src/Model/BoardPackage/BoardSquare.java
  src/View/BottomPanel.java
  src/View/ButtonPanel.java
  src/View/GamePanel.java
  src/View/GameView.java
  src/View/PlayerDetailPanel.java
  src/View/PlayerToken.java
  src/View/SidePanel.java
  src/View/TextPanel.java
Labels: feature

#182 Fixed Text Area in PlayerDetail. Reorganized PlayerDetail layout.
  src/View/PlayerDetailPanel.java
Labels: feature

#184 Feature/181 create user hint
  Tests/Veiw/PropertySpaceDemo.java
  src/Controller/GameController.java
  src/Controller/GameTextController.java
  src/Monopoly.java
  src/MonopolyTextGame.java
  src/View/TextPanel.java
  src/view/BoardSpaces/CardSpace.java
  src/view/BoardSpaces/FreeParkingSpace.java
  src/view/BoardSpaces/GoSpace.java
  src/view/BoardSpaces/GoToJailSpace.java
  src/view/BoardSpaces/HousingPanel.java
  src/view/BoardSpaces/JailSpace.java
  src/view/BoardSpaces/PropertySpace.java
  src/view/BoardSpaces/RailRoadSpace.java
  src/view/BoardSpaces/Spaces.java
  src/view/BoardSpaces/TaxSpace.java
  src/view/BoardSpaces/UtilitiesSpace.java
  src/view/ButtonPanel.java
  src/view/GamePanel.java
  src/view/GameTextView.java
  src/view/GameView.java
  src/view/PlayerDetailPanel.java
  src/view/PlayerToken.java
  src/view/TextPanel.java
Labels: feature

#188 Feature/186 create new game dialog
  src/Controller/GameController.java
  src/Model/GamePackage/Game.java
  src/Model/GamePackage/Player.java
  src/Monopoly.java
  src/view/BoardSpaces/Spaces.java
  src/view/GamePanel.java
  src/view/GameView.java
  src/view/NewGameDialog.java
  src/view/PlayerToken.java
Labels: feature

#192 Wrote comments for GamePanel. Changed Buttons in ButtonPanel.
  src/view/ButtonPanel.java
  src/view/GamePanel.java
Labels: feature

#193 Feateure/191 create initialization functionality
  src/Controller/GameController.java
  src/Model/GamePackage/Game.java
  src/Monopoly.java
  src/view/GamePanel.java
  src/view/GameView.java
  src/view/NewGameDialog.java
Labels: feature

#195 Add ActionListeners to Buttons
  src/Controller/GameController.java
  src/view/ButtonPanel.java
  src/view/GamePanel.java
  src/view/GameView.java
  src/view/NewGameDialog.java
Labels: feature

#199 Feature/198 implement buttton checking
  src/Controller/GameController.java
  src/view/ButtonPanel.java
  src/view/GameView.java
  src/view/boardspaces/Spaces.java
Labels: feature

#216 Deleted PlayerToken class.
  src/view/PlayerToken.java
  src/view/boardspaces/Spaces.java
Labels: setup

#217 Fixed new game logic for the view.
  src/Controller/GameController.java
  src/view/GamePanel.java
  src/view/boardspaces/Spaces.java
Labels: bug

#219 Fixed draw logic with regards to the view.
  src/Controller/GameController.java
Labels: bug

#226 Bug/223 made new game not close game
  src/Controller/GameController.java
  src/view/NewGameDialog.java
Labels: bug

#228 Added US board
  res/board.txt
  res/uk_board.txt
  src/view/GamePanel.java
Labels: bug

#229 fixed actions issue where every player receiving money was sent to go.
  res/community.txt
  src/Model/GamePackage/Die.java
  src/Model/GamePackage/Game.java
Labels: bug

#238 added teting menu item, dialog and became a god
  src/Controller/GameController.java
  src/view/GameView.java
  src/view/MenuPanel.java
Labels: feature
